%YAML 1.2
# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# Copyright (c) 2022-2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
---
id: [0x8cb3337174ac212d, 0xbc50c357f903c978]
name: RectifyParamsGenerator
version: 1.0.0
components:
  - id: [0xb0d9b38651b852c5, 0xb08a47f352c5ed17]
    type: nvidia::isaac::RectifyParamsGenerator
    input_output_groups:
      - input_keys: [left_camera_input, right_camera_input]
        output_keys: [left_camera_output, right_camera_output]
        input_format_keys: []
        output_format_keys: []
        supported_formats:
          - platforms: [any]
            details:
              - input_formats: [nitros_image_rgb8, nitros_image_rgb8]
                output_formats: [nitros_image_rgb8, nitros_image_rgb8]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
              - input_formats: [nitros_image_nv12, nitros_image_nv12]
                output_formats: [nitros_image_nv12, nitros_image_nv12]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
              - input_formats: [nitros_image_nv24, nitros_image_nv24]
                output_formats: [nitros_image_nv24, nitros_image_nv24]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
---
id: [0x950407cfab192bdf, 0x935173a7d5397635]
name: StereoCameraSynchronizer
version: 1.0.0
components:
  - id: [0xb882c328d10bfb25, 0xb5bd273adfa3f62a]
    type: nvidia::isaac::StereoCameraSynchronizer
    input_output_groups:
      - input_keys: [rx_left_camera, rx_right_camera]
        output_keys: [tx_left_camera, tx_right_camera]
        input_format_keys: []
        output_format_keys: []
        supported_formats:
          - platforms: [any]
            details:
              - input_formats: [nitros_image_rgb8, nitros_image_rgb8]
                output_formats: [nitros_image_rgb8, nitros_image_rgb8]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
              - input_formats: [nitros_image_nv12, nitros_image_nv12]
                output_formats: [nitros_image_nv12, nitros_image_nv12]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
              - input_formats: [nitros_image_nv24, nitros_image_nv24]
                output_formats: [nitros_image_nv24, nitros_image_nv24]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
---
name: ArgusCameraStereoExtension
version: 3.0.2
components:
  - id: [0xb588dfe1eb627257, 0x9cb8b7ee7e86359a]
    type: nvidia::isaac::CameraProvider
  - id: [0xd94385e5b35b4634, 0x9adb0d214a3865f6]
    type: nvidia::isaac::PoseTree
  - id: [0xd0c4ddad486a4a91, 0xb69c8a5304b205ef]
    type: nvidia::isaac::PoseTreeSetup
  - id: [0xd0c4ddad486a4a91, 0xb69c8a5304b205ef]
    type: nvidia::isaac::AtlasFrontend
  - id: [0xd0c4ddad486a4a91, 0xb69c8a5304b205ef]
    type: nvidia::isaac::PoseTreeFrame
  - id: [0xd0c4ddad486a4a91, 0xb69c8a5304b205ef]
    type: nvidia::isaac::ArgusCamera
    format_remapping:
      nitros_image_nv12: 0
      nitros_image_nv24: 1
    input_output_groups:
      - input_keys: []
        output_keys: [left_camera_output, right_camera_output]
        input_format_keys: []
        output_format_keys: [output_format, output_format]
        supported_formats:
          - platforms: [any]
            details:
              - input_formats: []
                output_formats: [nitros_image_nv12, nitros_image_nv12]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
              - input_formats: []
                output_formats: [nitros_image_nv24, nitros_image_nv24]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
  - id: [0xfc4d7b4d8fcc4daa, 0xa286056e0fcafa78]
    type: nvidia::isaac::tensor_ops::StreamConvertColorFormat
    format_remapping:
      nitros_image_rgb8: RGB_U8
      nitros_image_bgr8: BGR_U8
      nitros_image_rgba8: RGBA_U8
      nitros_image_bgra8: BGRA_U8
      nitros_image_mono8: Y_U8
      nitros_image_mono16: Y_U16
      nitros_image_rgb16: RGB_U16
      nitros_image_bgr16: BGR_U16
      nitros_image_nv12: NV12
      nitros_image_nv24: NV24
    input_output_groups:
      - input_keys: [receiver]
        output_keys: [transmitter]
        input_format_keys: []
        output_format_keys: [output_type]
        supported_formats:
          - platforms: [any]
            details:
              - input_formats: [nitros_image_nv24]
                output_formats: [nitros_image_nv24]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
              - input_formats: [nitros_image_nv12]
                output_formats: [nitros_image_rgb8]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
              - input_formats: [nitros_image_nv12]
                output_formats: [nitros_image_nv12]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
  - id: [0xfc4d7b4d8fcc4daa, 0xa286056e0fcafa78]
    type: nvidia::isaac::tensor_ops::ImageAdapter
  - id: [0xfc4d7b4d8fcc4daa, 0xa286056e0fcafa78]
    type: nvidia::isaac::tensor_ops::TensorStream
  - id: [0xfc4d7b4d8fcc4daa, 0xa286056e0fcafa78]
    type: nvidia::isaac_ros::MessageSplitter
    input_output_groups:
      - input_keys: [rx]
        output_keys: [image_tx, camera_model_tx]
        input_format_keys: []
        output_format_keys: []
        supported_formats:
          - platforms: [any]
            details:
              - input_formats: [nitros_image_rgb8]
                output_formats: [nitros_image_rgb8, nitros_camera_info]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
              - input_formats: [nitros_image_nv12]
                output_formats: [nitros_image_nv12, nitros_camera_info]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
              - input_formats: [nitros_image_nv24]
                output_formats: [nitros_image_nv24, nitros_camera_info]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
  - id: [0x8eec637e18b484f3, 0xa64f576e9be00941]
    type: nvidia::isaac::TimestampTranslator
    input_output_groups:
      - input_keys: [rx_correlated_timestamps, rx_tsc_message]
        output_keys: [tx_sys_message]
        input_format_keys: []
        output_format_keys: []
        supported_formats:
          - platforms: [any]
            details:
              - input_formats: [nitros_correlated_timestamp, nitros_accel]
                output_formats: [nitros_accel]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
              - input_formats: [nitros_correlated_timestamp, nitros_gyro]
                output_formats: [nitros_gyro]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
              - input_formats: [nitros_correlated_timestamp, nitros_image_nv24]
                output_formats: [nitros_image_nv24]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
              - input_formats: [nitros_correlated_timestamp, nitros_image_nv12]
                output_formats: [nitros_image_nv12]
                costs:
                  throughput: 10bytes/s
                  latency: 10ms
                  power: 100J
                  accuracy: 100%
